# 100 numpy exercises Solutions

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)


In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)


In [ ]:
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 3. Create a null vector of size 10 (★☆☆)


In [ ]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)


In [ ]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

# Simpler alternative
print("%d bytes" % Z.nbytes)

800 bytes
800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)


```
python -c "import numpy; numpy.info(numpy.add)"
```

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [ ]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)


In [ ]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)


In [ ]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)


In [ ]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)


In [ ]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)


In [ ]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)


In [ ]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.57810348 0.00107417 0.1851031 ]
  [0.17605532 0.24033557 0.9026133 ]
  [0.91962671 0.7971388  0.16723341]]

 [[0.77458218 0.55645335 0.59868699]
  [0.68868044 0.51731893 0.88822969]
  [0.08287445 0.66649686 0.31390225]]

 [[0.09136051 0.68929994 0.36027965]
  [0.66018668 0.94902642 0.10000522]
  [0.46503141 0.5893246  0.59424022]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


In [ ]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.015544286066721202 0.9954194775962317


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)


In [ ]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5750096411710012


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)


In [ ]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)


In [ ]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)


In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)


In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)


In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)


In [ ]:
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)


In [ ]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)


In [ ]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 1.260339   -0.89694024  0.82022203 -1.31724691 -1.50727137]
 [ 1.2892062   0.41828642  1.16874871 -0.59601233 -0.02294226]
 [ 0.79852227 -1.02823365  1.04810738 -0.90633372 -0.38409666]
 [ 1.02111329  1.07096734 -1.11846892  0.34674238  0.96462653]
 [-1.39517388 -1.15201279 -0.5387764  -0.75225778  1.40888536]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)


In [ ]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)


In [ ]:
Z = np.matmul(np.ones((5, 3)), np.ones((3, 2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)


In [ ]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)


In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)


```
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
import numpy as np
Z = np.arange(5)
Z

array([0, 1, 2, 3, 4])

On checking all of them one by one we get these as legal Expressions:

```
Z ** Z
2 << Z >> 2
1j * Z
Z / 1 / 1
```

And these are illegal Expressions:
```
Z <- Z ❌ Illegal in Python.
The <- operator does not exist (it’s from R, not Python).
You’ll get a SyntaxError.


Z < Z > Z ❌ Illegal for NumPy arrays.
Chained comparisons like Z < Z > Z are not supported element-wise — you’ll get a ValueError.

```

#### 28. What are the result of the following expressions? (★☆☆)


In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan

0

[-9.22337204e+18]

#### 29. How to round away from zero a float array ? (★☆☆)


In [ ]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ -6.   4.  -3.   8.   1.  -8.   9.   6. -10.  -3.]
[ -6.   4.  -3.   8.   1.  -8.   9.   6. -10.  -3.]


#### 30. How to find common values between two arrays? (★☆☆)


In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[3 4 7 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)


In [ ]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)


In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/tmp/ipython-input-2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)


In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)
print(yesterday)

2025-11-04


In [ ]:
today     = np.datetime64('today')
print(today)

2025-11-05


In [ ]:
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(tomorrow)

2025-11-06


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)


In [ ]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)


In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
print(np.add(A,B,out=B))
print(np.divide(A,2,out=A))
print(np.negative(A,out=A))
print(np.multiply(A,B,out=A))

[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)


In [ ]:
Z = np.random.uniform(0,10,10)
Z

array([3.54989045, 9.55283381, 5.8620618 , 2.58370755, 9.99902727,
       6.4909425 , 8.48433885, 1.07326085, 8.01758253, 1.6946425 ])

In [ ]:
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[3. 9. 5. 2. 9. 6. 8. 1. 8. 1.]
[3. 9. 5. 2. 9. 6. 8. 1. 8. 1.]
[3. 9. 5. 2. 9. 6. 8. 1. 8. 1.]
[3 9 5 2 9 6 8 1 8 1]
[3. 9. 5. 2. 9. 6. 8. 1. 8. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)


In [ ]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)


In [ ]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)


In [ ]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.20216403 0.37090097 0.39449758 0.42153312 0.48711181 0.61579716
 0.76706393 0.80141532 0.90719306 0.91469054]


#### 41. How to sum a small array faster than np.sum? (★★☆)


In [ ]:
Z = np.arange(10)
np.add.reduce(Z)

np.int64(45)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)


In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)


In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)


In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.14414096 1.10426374 1.14171228 0.61252511 1.12846905 0.77103711
 1.04536202 0.87301674 0.55756313 0.91499406]
[0.71854716 0.7981131  0.71719599 0.27155563 0.48480006 0.33683089
 1.03327007 1.26300821 0.48365803 1.0838489 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)


In [ ]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.7046064  0.45519564 0.30180168 0.46857948 0.60095425 0.46444781
 0.72283359 0.78365009 0.14149562 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)


In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))

print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)


In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)


In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)


In [ ]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)


In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)


In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)


In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy

import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.58970005 0.69313101 0.43504425 0.21599865 0.4420383
  0.39084118 0.74745762 0.02736233 0.28893416]
 [0.58970005 0.         1.06504667 0.15620348 0.37413299 0.81313787
  0.875146   0.72613687 0.60390632 0.81441355]
 [0.69313101 1.06504667 0.         0.93334277 0.80811695 0.26539779
  0.32495977 0.58195411 0.66605668 0.85659689]
 [0.43504425 0.15620348 0.93334277 0.         0.22091752 0.67487021
  0.72496719 0.6656389  0.44840486 0.67211756]
 [0.21599865 0.37413299 0.80811695 0.22091752 0.         0.54276902
  0.55085421 0.69376597 0.23205112 0.45871962]
 [0.4420383  0.81313787 0.26539779 0.67487021 0.54276902 0.
  0.16709854 0.48721604 0.41595763 0.64938995]
 [0.39084118 0.875146   0.32495977 0.72496719 0.55085421 0.16709854
  0.         0.65179666 0.36359082 0.53192488]
 [0.74745762 0.72613687 0.58195411 0.6656389  0.69376597 0.48721604
  0.65179666 0.         0.73235621 1.02676591]
 [0.02736233 0.60390632 0.66605668 0.44840486 0.23205112 0.41595763
  0.36359082 0.732356

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?


In [ ]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[13 52 23 68 23  1 50  2 74 58]


#### 54. How to read the following file? (★★☆)


```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)


In [2]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)


In [3]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)


In [4]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)


In [5]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.52849226 -0.38934707 -0.03898425  0.47564426  0.3477261   0.03029992
   0.01870323 -0.17738607 -0.41390866 -0.38123972]
 [-0.24650529 -0.35967688 -0.29777055  0.47396647  0.08180002 -0.34738956
  -0.25309837  0.38424216  0.08683464  0.47759736]
 [-0.32333044  0.3946192  -0.26759107 -0.22060781  0.02538567  0.27437713
   0.18054469  0.47961807 -0.16159241 -0.38142303]
 [ 0.06289785  0.10408471 -0.01913987  0.1746518   0.03119676 -0.30553509
   0.21715246  0.27914951 -0.2855292  -0.25892893]
 [-0.51475162 -0.19793469  0.35259333  0.01162494  0.29758551  0.1802342
  -0.26776939  0.05602017  0.3510257  -0.26862815]]


#### 59. How to sort an array by the nth column? (★★☆)


In [6]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[0 3 2]
 [1 0 3]
 [4 0 8]]
[[1 0 3]
 [4 0 8]
 [0 3 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)


In [8]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

False
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)


In [7]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4901001960511293


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)


In [9]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)


In [10]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)


In [11]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 3. 6. 3. 3. 3. 3. 3. 3. 2.]


In [12]:
# Another solution
np.add.at(Z, I, 1)
print(Z)

[ 1.  5. 11.  5.  5.  5.  5.  5.  5.  3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)


In [13]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)


In [14]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)


In [16]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[31 51 57 46]
 [40 60 49 60]
 [48 59 64 50]]
[[31 51 57 46]
 [40 60 49 60]
 [48 59 64 50]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)


In [17]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

import pandas as pd
print(pd.Series(D).groupby(S).mean())


[0.50791842 0.69324564 0.55082628 0.30602737 0.50890414 0.62174331
 0.60485654 0.56004565 0.49903981 0.5165102 ]
0    0.507918
1    0.693246
2    0.550826
3    0.306027
4    0.508904
5    0.621743
6    0.604857
7    0.560046
8    0.499040
9    0.516510
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)


In [19]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

array([1.08605914, 1.34719575, 1.02650257, 2.05884811, 1.37939815])

In [20]:
# Fast version
np.sum(A * B.T, axis=1)

array([1.08605914, 1.34719575, 1.02650257, 2.05884811, 1.37939815])

In [21]:
# Faster version
np.einsum("ij,ji->i", A, B)

array([1.08605914, 1.34719575, 1.02650257, 2.05884811, 1.37939815])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)


In [22]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)


In [23]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)


In [24]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)


In [25]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 45) ( 1, 70) ( 2, 68) ( 2, 80) (17, 50) (17, 55) (17, 57) (18, 29)
 (18, 73) (19, 59) (19, 77) (21, 52) (21, 58) (29, 50) (29, 73) (29, 74)
 (33, 73) (33, 94) (45, 70) (50, 57) (50, 74) (52, 58) (55, 55) (59, 77)
 (63, 65) (63, 89) (65, 89) (68, 80) (73, 94)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)


In [26]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)


In [27]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)


In [28]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)


In [29]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.10726331,  0.90842781, -0.37164473,  0.9614772 ,  0.95935647,
        0.31736386, -0.48893218, -0.55822739, -0.1620802 , -0.89939664,
        0.25490839,  0.14160965,  0.62038192, -0.26825261,  0.99514734,
        0.3903797 ,  0.64471168,  0.74666101, -0.11663808,  0.78510742,
        0.33265248,  0.12281218, -0.31494275, -0.83525906,  0.65679631,
       -0.48193824, -0.93361137, -0.68351656, -0.51285934,  0.11003062,
       -0.93371126, -0.97274862,  0.24606274,  0.60632527,  0.55348778,
       -0.74564977, -0.46797527, -0.62315745,  0.47740845, -0.49882975,
        0.81882704,  0.33097006,  0.67747985, -0.9661642 , -0.69297869,
        0.94060753,  0.44004197,  0.77072759,  0.292488  , -0.88030546,
       -0.0083674 , -0.49861052,  0.44914101, -0.94774613,  0.8554717 ,
        0.54722462,  0.35661232,  0.58348608,  0.10682382, -0.33972441,
        0.16317309, -0.85808663,  0.38170757,  0.67163141,  0.69105878,
       -0.37320141,  0.48934848, -0.54951419, -0.8901968 ,  0.02

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)


In [32]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

def distance_faster(P0,P1,p):
    v = P1- P0
    v[:,[0,1]] = v[:,[1,0]]
    v[:,1]*=-1
    norm = np.linalg.norm(v,axis=1)
    r = P0 - p
    d = np.abs(np.einsum("ij,ij->i",r,v)) / norm

    return d

print(distance_faster(P0, P1, p))

[0.91277677 7.62340587 2.40952408 1.96851749 6.59802291 6.78624579
 3.19346959 1.91418602 7.81634037 7.74455501]


In [31]:
##--------------- OR ---------------##
def distance_slower(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

print(distance_slower(P0, P1, p))

[10.49349782 11.1631909   7.10102745 13.08325222  3.40312549 12.79054294
  2.60874662 14.39654216  5.12705794  4.42547244]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)


In [36]:
import numpy as np

def distance_points_to_lines(p: np.ndarray, p_1: np.ndarray, p_2: np.ndarray) -> np.ndarray:
    """
    Parameters
    ----------
    p : np.ndarray, shape (m, 2)
        Set of 2D points.
    p_1 : np.ndarray, shape (n, 2)
        Starting points (first endpoints) of n lines.
    p_2 : np.ndarray, shape (n, 2)
        Ending points (second endpoints) of n lines.

    Returns
    -------
    distances : np.ndarray, shape (m, n)
        distances[j, i] = perpendicular distance from point p[j] to line i.
    """

    # --------------------------
    # STEP 1: Unpack coordinates
    # --------------------------
    # Transpose to separate x and y components for all points and line endpoints.
    x_0, y_0 = p.T     # Coordinates of m points
    x_1, y_1 = p_1.T   # Coordinates of first endpoints of n lines
    x_2, y_2 = p_2.T   # Coordinates of second endpoints of n lines

    # -----------------------------------------------
    # STEP 2: Compute line direction vector components
    # -----------------------------------------------
    dx = x_2 - x_1     # Δx = difference in x for each line
    dy = y_2 - y_1     # Δy = difference in y for each line

    # ---------------------------------------------------
    # STEP 3: Precompute constant term of line equation
    # Line equation (Ax + By + C = 0) → C = x2*y1 - y2*x1
    # ---------------------------------------------------
    cross_term = x_2 * y_1 - y_2 * x_1  # Shape (n,)

    # ---------------------------------------------------------------------
    # STEP 4: Compute numerator of distance formula for all points & lines
    # Formula: |A*x0 + B*y0 + C|
    # Broadcasting shapes:
    #   dy[np.newaxis, :] → (1, n)  ← coefficients of lines
    #   x_0[:, np.newaxis] → (m, 1) ← coordinates of points
    # Result → (m, n) matrix of all point-line combinations
    # ---------------------------------------------------------------------
    numerator = np.abs(
        dy[np.newaxis, :] * x_0[:, np.newaxis]     # dy * x0
        - dx[np.newaxis, :] * y_0[:, np.newaxis]   # -dx * y0
        + cross_term[np.newaxis, :]                # + cross_term
    )

    # ---------------------------------------------------
    # STEP 5: Compute denominator = sqrt(A² + B²)
    # Same for all points but different per line
    # ---------------------------------------------------
    denominator = np.sqrt(dx**2 + dy**2)  # Shape (n,)

    # -------------------------------------------------------------------
    # STEP 6: Divide numerator by denominator using broadcasting
    # Result: distances[j, i] = distance from point j to line i
    # -------------------------------------------------------------------
    distances = numerator / denominator[np.newaxis, :]
    return distances

#Example Usage
P0 = np.random.uniform(-10, 10, (10, 2))  # 10 line start points
P1 = np.random.uniform(-10, 10, (10, 2))  # 10 line end points
P  = np.random.uniform(-10, 10, (5, 2))   # 5 query points

D = distance_points_to_lines(P, P0, P1)
print("Shape of distance matrix:", D.shape)  # (5, 10)
print(D)

Shape of distance matrix: (5, 10)
[[ 1.75814813  6.47682572 10.31813044  3.11913746  0.05373136  6.09749266
   8.06276214  6.82315601  4.77454948 10.13657389]
 [ 5.62538133 10.78644327  7.82612536  9.63544602  1.1151999   2.16488382
   6.51169255  6.54048359 13.13180584 12.81399386]
 [ 3.87491747 12.38811583 13.51700664  3.23238767  3.97320091  3.23853945
  11.8219473  11.2438371   9.32584158 15.69462512]
 [ 7.96575158  0.34807646  6.18896662  3.56971026  5.06422029  8.84008398
   3.33480085  1.40249395  0.02484588  3.59529558]
 [13.67153328  7.08851595  1.48520704  4.84917121 10.53115542 10.74743203
   1.89128719  4.40575963  4.11126261  3.04332632]]


#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)


In [39]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = tuple([slice(start,stop) for start,stop in zip(R_start,R_stop)])
z = tuple([slice(start,stop) for start,stop in zip(Z_start,Z_stop)])
R[r] = Z[z]
print(Z,"\n")
print(R)

[[8 0 8 9 0 9 6 3 1 0]
 [4 3 6 2 9 1 0 1 8 0]
 [3 2 8 7 7 6 5 0 4 8]
 [9 5 3 2 1 3 6 9 6 6]
 [7 7 4 6 8 2 4 2 6 4]
 [4 3 5 1 1 6 1 8 8 7]
 [1 7 0 5 8 5 2 6 9 0]
 [2 7 5 3 1 0 4 7 7 1]
 [2 4 1 4 9 9 5 0 7 3]
 [5 6 7 9 6 5 2 7 4 3]] 

[[0 0 0 0 0]
 [0 8 0 8 9]
 [0 4 3 6 2]
 [0 3 2 8 7]
 [0 9 5 3 2]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)


In [41]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R,"\n")

Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]] 

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★☆)


In [42]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
threshold = len(S) * S.max() * np.finfo(S.dtype).eps
rank = np.sum(S > threshold)
print(rank)

10


In [43]:
# alternative solution:
rank = np.linalg.matrix_rank(Z)
print(rank)

10


#### 83. How to find the most frequent value in an array? (★☆☆)


In [45]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

6


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)


In [48]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 2 4]
   [1 4 1]
   [4 4 1]]

  [[2 4 2]
   [4 1 2]
   [4 1 2]]

  [[4 2 0]
   [1 2 3]
   [1 2 4]]

  [[2 0 4]
   [2 3 4]
   [2 4 0]]

  [[0 4 3]
   [3 4 0]
   [4 0 0]]

  [[4 3 4]
   [4 0 1]
   [0 0 0]]

  [[3 4 3]
   [0 1 4]
   [0 0 3]]

  [[4 3 4]
   [1 4 2]
   [0 3 3]]]


 [[[1 4 1]
   [4 4 1]
   [0 3 0]]

  [[4 1 2]
   [4 1 2]
   [3 0 3]]

  [[1 2 3]
   [1 2 4]
   [0 3 3]]

  [[2 3 4]
   [2 4 0]
   [3 3 4]]

  [[3 4 0]
   [4 0 0]
   [3 4 0]]

  [[4 0 1]
   [0 0 0]
   [4 0 4]]

  [[0 1 4]
   [0 0 3]
   [0 4 4]]

  [[1 4 2]
   [0 3 3]
   [4 4 4]]]


 [[[4 4 1]
   [0 3 0]
   [3 2 3]]

  [[4 1 2]
   [3 0 3]
   [2 3 4]]

  [[1 2 4]
   [0 3 3]
   [3 4 0]]

  [[2 4 0]
   [3 3 4]
   [4 0 4]]

  [[4 0 0]
   [3 4 0]
   [0 4 1]]

  [[0 0 0]
   [4 0 4]
   [4 1 1]]

  [[0 0 3]
   [0 4 4]
   [1 1 3]]

  [[0 3 3]
   [4 4 4]
   [1 3 0]]]


 [[[0 3 0]
   [3 2 3]
   [4 2 1]]

  [[3 0 3]
   [2 3 4]
   [2 1 4]]

  [[0 3 3]
   [3 4 0]
   [1 4 0]]

  [[3 3 4]
   [4 0 4]
   [4 0 1]]

  [[3 4 0]
   

In [50]:
Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[3 0 2]
   [2 4 2]
   [2 4 3]]

  [[0 2 3]
   [4 2 2]
   [4 3 4]]

  [[2 3 0]
   [2 2 0]
   [3 4 0]]

  [[3 0 1]
   [2 0 1]
   [4 0 1]]

  [[0 1 2]
   [0 1 2]
   [0 1 2]]

  [[1 2 1]
   [1 2 2]
   [1 2 2]]

  [[2 1 1]
   [2 2 0]
   [2 2 2]]

  [[1 1 3]
   [2 0 0]
   [2 2 3]]]


 [[[2 4 2]
   [2 4 3]
   [4 1 2]]

  [[4 2 2]
   [4 3 4]
   [1 2 3]]

  [[2 2 0]
   [3 4 0]
   [2 3 4]]

  [[2 0 1]
   [4 0 1]
   [3 4 1]]

  [[0 1 2]
   [0 1 2]
   [4 1 2]]

  [[1 2 2]
   [1 2 2]
   [1 2 3]]

  [[2 2 0]
   [2 2 2]
   [2 3 3]]

  [[2 0 0]
   [2 2 3]
   [3 3 0]]]


 [[[2 4 3]
   [4 1 2]
   [1 2 0]]

  [[4 3 4]
   [1 2 3]
   [2 0 2]]

  [[3 4 0]
   [2 3 4]
   [0 2 3]]

  [[4 0 1]
   [3 4 1]
   [2 3 1]]

  [[0 1 2]
   [4 1 2]
   [3 1 4]]

  [[1 2 2]
   [1 2 3]
   [1 4 1]]

  [[2 2 2]
   [2 3 3]
   [4 1 0]]

  [[2 2 3]
   [3 3 0]
   [1 0 4]]]


 [[[4 1 2]
   [1 2 0]
   [4 4 2]]

  [[1 2 3]
   [2 0 2]
   [4 2 1]]

  [[2 3 4]
   [0 2 3]
   [2 1 2]]

  [[3 4 1]
   [2 3 1]
   [1 2 2]]

  [[4 1 2]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)


In [51]:
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7 14 13 17  5]
 [14  3 12 10 17]
 [13 12  7 42 13]
 [17 10 42  1  1]
 [ 5 17 13  1  3]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)


In [52]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★☆)


In [53]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [55]:
windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [57]:
# alternative solution:
S = Z.reshape(4, 4, 4, 4).sum((1, 3))
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)


In [58]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)


In [59]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)


In [60]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)


In [65]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np._core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)


In [67]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)

2.66 s ± 822 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [68]:
%timeit x*x*x

238 ms ± 5.27 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [69]:
%timeit np.einsum('i,i,i->i',x,x,x)

194 ms ± 3.04 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)


In [70]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 2 3 5 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)


In [74]:
Z = np.random.randint(0,5,(10,3))
print(Z)

[[4 3 4]
 [4 1 0]
 [3 4 1]
 [0 2 0]
 [0 4 1]
 [1 3 3]
 [3 4 3]
 [3 3 3]
 [1 3 2]
 [3 3 4]]


In [73]:
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[3 3 2]
 [3 4 3]
 [3 0 2]
 [4 4 1]
 [1 0 3]
 [2 3 2]
 [0 4 4]
 [4 4 3]
 [3 1 3]]


In [75]:
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 3 4]
 [4 1 0]
 [3 4 1]
 [0 2 0]
 [0 4 1]
 [1 3 3]
 [3 4 3]
 [1 3 2]
 [3 3 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)


In [77]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [78]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)


In [80]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 0]
 [1 0 0]]


In [81]:
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [0 1 0]
 [1 0 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)


In [82]:
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[1.02408705e-01, 1.52448065e-03, 1.28298249e-01, 1.28842989e-01,
        3.01647538e-02, 1.24833859e-01, 9.39574756e-02, 9.10930059e-02,
        7.53164222e-02, 2.20921669e-02],
       [3.14207750e-01, 4.67737228e-03, 3.93641383e-01, 3.95312740e-01,
        9.25507205e-02, 3.83012030e-01, 2.88277906e-01, 2.79489214e-01,
        2.31083906e-01, 6.77826174e-02],
       [1.79215035e-01, 2.66783819e-03, 2.24521687e-01, 2.25474981e-01,
        5.27882607e-02, 2.18459011e-01, 1.64425400e-01, 1.59412584e-01,
        1.31803593e-01, 3.86612493e-02],
       [1.78188821e-01, 2.65256173e-03, 2.23236040e-01, 2.24183875e-01,
        5.24859867e-02, 2.17208080e-01, 1.63483874e-01, 1.58499762e-01,
        1.31048865e-01, 3.84398688e-02],
       [2.60067386e-02, 3.87142577e-04, 3.25814005e-02, 3.27197375e-02,
        7.66035337e-03, 3.17016170e-02, 2.38605450e-02, 2.31331116e-02,
        1.91266407e-02, 5.61031614e-03],
       [3.92273571e-01, 5.83947890e-03, 4.91442720e-01, 4.93529330e-01,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?


In [83]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)


In [84]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)


In [85]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.14473123  0.24699237]
